
name: Expressions & Contexts
on:
  [pull_request, issues, workflow_dispatch]

jobs:
  runs-on-issues: 
    runs-on: ubuntu-latest
    if: contains('hello', 'll') 
  using-expressions: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        run: |
          echo "Hello ${{ 1 }}"
          echo "Hello ${{ 'this is a string' }}"
          echo "Hello ${{ null }}"
          echo "Hello ${{ true }}"
          echo "Hello ${{ 1 > 2 }}"
          echo "Hello ${{ 'true' == 'String' }}"
          echo "Hello ${{ true && false }}"
      - name: Dump Contaxts
        run: |
          echo 'Github Context${{ toJson(github) }}'
          echo 'Jobs Context ${{ toJson(job) }}'
          echo 'Steps Context ${{ toJson(steps) }}'
          echo 'Secrets Context ${{ toJson(secrets) }}'
          echo 'Runner Context${{ toJson(runner) }}'