name: Matrix
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [14.x, 15.x, 16.x]
    steps:
        - run: node -v
        - uses: actions/setup-node@v3
          with:
                node-version: ${{ matrix.node-version}}
        - run: node -v
