name: Prerequisites-Phase01
on: 
    workflow_dispatch:


jobs:
  Run-Prerequisites-Phase01:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run Prerequisites-Phase01
          run: .\Prerequisites-Phase01.ps1
  
