name: Prerequisites-Phase01
on: 
    push:


jobs:
  Run-Prerequisites-Phase01:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Get Present Working Directory
          run: echo "Present Working Directory is $PWD"
        - name: Get List of Files
          run: get-childitem -recurse 
        - name: Run Prerequisites-Phase01
          run: ./Tasks/Task001/Task001.ps1

  
